"""
test_phase17.py — Tests for Phase 17: Professional PDF Report Generation.

Tests for export_service.generate_pdf() — verifies PDF structure, content,
privacy, and resilience using pdfplumber to extract text from generated bytes.

Test list:
  1.  test_generate_pdf_returns_bytes
  2.  test_generate_pdf_contains_no_pii
  3.  test_generate_pdf_contains_gross_and_net
  4.  test_generate_pdf_contains_insights
  5.  test_generate_pdf_legal_disclaimer_present
  6.  test_generate_pdf_empty_insights_and_anomalies
"""

import io
import pytest
import pdfplumber

from app.models.schemas import (
    ParsedSlipPayload,
    SummaryTotals,
    SlipMeta,
    LineItem,
    Anomaly,
    Insight,
)
from app.services.export_service import generate_pdf


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_summary(**overrides) -> SummaryTotals:
    """Build a minimal SummaryTotals with sensible defaults."""
    defaults = {
        "gross": 25_089.32,
        "gross_confidence": 0.95,
        "net": 14_339.60,
        "net_confidence": 0.95,
        "total_deductions": 10_749.72,
        "total_employer_contributions": None,
        "income_tax": 6_119.00,
        "national_insurance": 1_500.00,
        "health_insurance": 1_387.00,
        "pension_employee": 1_504.00,
        "integrity_ok": True,
        "integrity_notes": [],
        "total_payments_other": None,
        "mandatory_taxes_total": None,
        "provident_funds_deduction": None,
        "other_deductions": None,
        "net_salary": None,
        "net_to_pay": None,
        "gross_taxable": 29_885.00,
        "gross_ni": 24_000.00,
        "credit_points": 2.25,
    }
    defaults.update(overrides)
    return SummaryTotals(**defaults)


def _make_slip_meta(**overrides) -> SlipMeta:
    """Build a minimal SlipMeta."""
    defaults = {
        "pay_month": "2024-03",
        "provider_guess": "hilan",
        "confidence": 0.9,
        "employer_name": None,       # always null — privacy by construction
        "employee_name_redacted": True,
    }
    defaults.update(overrides)
    return SlipMeta(**defaults)


def _make_line_items() -> list[LineItem]:
    """Return a small list of representative line items."""
    return [
        LineItem(
            id="li_001",
            category="earning",
            description_hebrew="שכר בסיס",
            explanation_hebrew="שכר בסיס חודשי",
            value=25_089.32,
            raw_text=None,
            confidence=0.95,
            page_index=0,
            is_unknown=False,
            unknown_guesses=[],
            unknown_question=None,
            quantity=186.0,
            rate=134.89,
        ),
        LineItem(
            id="li_002",
            category="deduction",
            description_hebrew="מס הכנסה",
            explanation_hebrew="מס הכנסה חודשי",
            value=6_119.00,
            raw_text=None,
            confidence=0.95,
            page_index=0,
            is_unknown=False,
            unknown_guesses=[],
            unknown_question=None,
            quantity=None,
            rate=None,
        ),
        LineItem(
            id="li_003",
            category="deduction",
            description_hebrew="ביטוח לאומי",
            explanation_hebrew="ביטוח לאומי עובד",
            value=1_500.00,
            raw_text=None,
            confidence=0.95,
            page_index=0,
            is_unknown=False,
            unknown_guesses=[],
            unknown_question=None,
            quantity=None,
            rate=None,
        ),
    ]


def _make_insights() -> list[Insight]:
    """Return two sample insights (one success, one info)."""
    return [
        Insight(
            id="ins_min_wage_ok",
            kind="success",
            title="שכר הבסיס תקין",
            body="שכר הבסיס שלך תקין וגבוה משכר המינימום החוקי.",
        ),
        Insight(
            id="ins_havraa_explained",
            kind="info",
            title="דמי הבראה — מה זה?",
            body="שולמו לך דמי הבראה. זהו תשלום שנתי המגיע לכל עובד/ת לאחר שנת ותק.",
        ),
    ]


def _make_anomalies() -> list[Anomaly]:
    """Return one sample anomaly."""
    return [
        Anomaly(
            id="anom_001",
            severity="Warning",
            what_we_found="ניכוי פנסיה נמוך ממינימום החובה",
            why_suspicious="שיעור הפנסיה נמוך מ-6%",
            what_to_do="יש לבדוק מול מחלקת השכר",
            ask_payroll="מהו שיעור הפנסיה בתלוש?",
            related_line_item_ids=[],
        ),
    ]


def _make_payload(**overrides) -> ParsedSlipPayload:
    """Build a full ParsedSlipPayload for testing."""
    defaults = {
        "slip_meta": _make_slip_meta(),
        "summary": _make_summary(),
        "line_items": _make_line_items(),
        "anomalies": _make_anomalies(),
        "insights": _make_insights(),
        "blocks": [],
        "tax_credits_detected": None,
        "answers_applied": True,
        "error_code": None,
        "parse_source": "pdf_text_layer",
        "ocr_debug_preview": None,
        "ytd": None,
        "balances": [],
        "corrections": [],
    }
    defaults.update(overrides)
    return ParsedSlipPayload(**defaults)


def _extract_text(pdf_bytes: bytes) -> str:
    """Extract all text from a PDF bytes object using pdfplumber."""
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        pages_text = [page.extract_text() or "" for page in pdf.pages]
    return "\n".join(pages_text)


# ---------------------------------------------------------------------------
# 1. generate_pdf returns a non-empty bytes object
# ---------------------------------------------------------------------------

def test_generate_pdf_returns_bytes():
    """
    generate_pdf() must return a bytes object of reasonable size.
    A valid single-page PDF with Hebrew content should be >1000 bytes.
    """
    payload = _make_payload()
    result = generate_pdf(payload)

    assert isinstance(result, bytes), "generate_pdf must return bytes"
    assert len(result) > 1_000, (
        f"PDF too small ({len(result)} bytes) — expected >1000 bytes for a valid PDF"
    )
    # All PDFs start with %PDF-
    assert result[:5] == b"%PDF-", "Result must be a valid PDF (starts with %PDF-)"


# ---------------------------------------------------------------------------
# 2. PDF contains no PII — generic placeholders only
# ---------------------------------------------------------------------------

def test_generate_pdf_contains_no_pii():
    """
    Privacy guarantee: employer_name and employee_name are always null.
    The PDF must use 'עובד/ת' and 'מעסיק' as generic placeholders.
    No actual names should appear.
    """
    payload = _make_payload()
    # Employer_name is always null in schema — verify PDF uses generic placeholder
    assert payload.slip_meta.employer_name is None, "employer_name must be null"

    pdf_bytes = generate_pdf(payload)
    text = _extract_text(pdf_bytes)

    # Generic placeholder must be present
    assert "עובד" in text, "PDF must contain 'עובד' generic placeholder"

    # No real PII names should appear
    pii_names = ["ישראל ישראלי", "חברה בע\"מ", "John Doe"]
    for name in pii_names:
        assert name not in text, f"PII name '{name}' must not appear in the PDF"


# ---------------------------------------------------------------------------
# 3. PDF contains gross and net monetary values
# ---------------------------------------------------------------------------

def test_generate_pdf_contains_gross_and_net():
    """
    The financial summary section must include the gross and net values.
    Numbers appear formatted as '₪25,089.32' and '₪14,339.60'.
    We check for the thousands-separated portion ('25,089' and '14,339').
    """
    payload = _make_payload()
    pdf_bytes = generate_pdf(payload)
    text = _extract_text(pdf_bytes)

    assert "25,089" in text, (
        f"PDF must contain gross value '25,089' in financial summary. "
        f"Extracted text (first 500 chars): {text[:500]}"
    )
    assert "14,339" in text, (
        f"PDF must contain net value '14,339' in financial summary. "
        f"Extracted text (first 500 chars): {text[:500]}"
    )


# ---------------------------------------------------------------------------
# 4. PDF contains insight titles
# ---------------------------------------------------------------------------

def test_generate_pdf_contains_insights():
    """
    The 'תובנות חכמות' section must include insight titles.
    Both the success insight and info insight titles must appear.
    """
    payload = _make_payload()
    pdf_bytes = generate_pdf(payload)
    text = _extract_text(pdf_bytes)

    assert "שכר הבסיס תקין" in text, (
        "PDF must contain the success insight title 'שכר הבסיס תקין'"
    )
    assert "דמי הבראה" in text, (
        "PDF must contain the info insight title about דמי הבראה"
    )
    assert "תובנות חכמות" in text, (
        "PDF must contain the 'תובנות חכמות' section header"
    )


# ---------------------------------------------------------------------------
# 5. PDF contains the legal disclaimer on every page
# ---------------------------------------------------------------------------

def test_generate_pdf_legal_disclaimer_present():
    """
    The footer legal disclaimer must appear on the generated PDF.
    Key phrase: 'חינוכיות בלבד' (educational purposes only).
    """
    payload = _make_payload()
    pdf_bytes = generate_pdf(payload)
    text = _extract_text(pdf_bytes)

    assert "חינוכיות בלבד" in text, (
        "Legal disclaimer 'חינוכיות בלבד' must appear in the PDF footer"
    )
    assert "תלוש ברור" in text, (
        "Legal disclaimer must mention 'תלוש ברור' system name"
    )


# ---------------------------------------------------------------------------
# 6. Empty insights and anomalies do not crash generate_pdf
# ---------------------------------------------------------------------------

def test_generate_pdf_empty_insights_and_anomalies():
    """
    generate_pdf must succeed even with zero insights and zero anomalies.
    This exercises the 'if payload.insights' and 'if payload.anomalies' guards.
    """
    payload = _make_payload(insights=[], anomalies=[])
    pdf_bytes = generate_pdf(payload)

    assert isinstance(pdf_bytes, bytes), "Must return bytes even with empty insights/anomalies"
    assert len(pdf_bytes) > 1_000, "PDF must still be non-trivial with empty lists"
    assert pdf_bytes[:5] == b"%PDF-", "Must still be a valid PDF"

    # Financial summary must still be present
    text = _extract_text(pdf_bytes)
    assert "25,089" in text, "Gross must still appear without insights/anomalies"
    assert "14,339" in text, "Net must still appear without insights/anomalies"
